spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/dating_agency_new
    username: student
    password: 1234

  jpa:
        generate-ddl: true
        hibernate:
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
